/**
 ******************************************************************************
 * @file    LSM6DSL_ACC_GYRO_driver.h
 * @author  MEMS Application Team
 * @version V1.5
 * @date    17-May-2016
 * @brief   LSM6DSL header driver file
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; COPYRIGHT(c) 2017 STMicroelectronics</center></h2>
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *   1. Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 *   3. Neither the name of STMicroelectronics nor the names of its contributors
 *      may be used to endorse or promote products derived from this software
 *      without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************
 */
/*
 * Based on STMicroelectronics LSM6DSL driver
 * Modified by Neon Smart Studio for W-Link
 */
#ifndef LSM6DSL_REGISTER_DEF_H
#define LSM6DSL_REGISTER_DEF_H

#include <stdint.h>

/************** Who am I  *******************/

#define LSM6DSL_ACC_GYRO_WHO_AM_I         0x6A

/************** Device Register  *******************/

#define LSM6DSL_ACC_GYRO_FUNC_CFG_ACCESS  	0X01

#define LSM6DSL_ACC_GYRO_SENSOR_SYNC_TIME  	0X04
#define LSM6DSL_ACC_GYRO_SENSOR_RES_RATIO  	0X05

#define LSM6DSL_ACC_GYRO_FIFO_CTRL1  	0X06
#define LSM6DSL_ACC_GYRO_FIFO_CTRL2  	0X07
#define LSM6DSL_ACC_GYRO_FIFO_CTRL3  	0X08
#define LSM6DSL_ACC_GYRO_FIFO_CTRL4  	0X09
#define LSM6DSL_ACC_GYRO_FIFO_CTRL5  	0X0A

#define LSM6DSL_ACC_GYRO_DRDY_PULSE_CFG_G  	0X0B
#define LSM6DSL_ACC_GYRO_INT1_CTRL  	0X0D
#define LSM6DSL_ACC_GYRO_INT2_CTRL  	0X0E
#define LSM6DSL_ACC_GYRO_WHO_AM_I_REG  	0X0F
#define LSM6DSL_ACC_GYRO_CTRL1_XL  	0X10
#define LSM6DSL_ACC_GYRO_CTRL2_G  	0X11
#define LSM6DSL_ACC_GYRO_CTRL3_C  	0X12
#define LSM6DSL_ACC_GYRO_CTRL4_C  	0X13
#define LSM6DSL_ACC_GYRO_CTRL5_C  	0X14
#define LSM6DSL_ACC_GYRO_CTRL6_G  	0X15
#define LSM6DSL_ACC_GYRO_CTRL7_G  	0X16
#define LSM6DSL_ACC_GYRO_CTRL8_XL  	0X17
#define LSM6DSL_ACC_GYRO_CTRL9_XL  	0X18
#define LSM6DSL_ACC_GYRO_CTRL10_C  	0X19

#define LSM6DSL_ACC_GYRO_MASTER_CONFIG  	0X1A
#define LSM6DSL_ACC_GYRO_WAKE_UP_SRC  	0X1B
#define LSM6DSL_ACC_GYRO_TAP_SRC  	0X1C
#define LSM6DSL_ACC_GYRO_D6D_SRC  	0X1D
#define LSM6DSL_ACC_GYRO_STATUS_REG  	0X1E

#define LSM6DSL_ACC_GYRO_OUT_TEMP_L  	0X20
#define LSM6DSL_ACC_GYRO_OUT_TEMP_H  	0X21
#define LSM6DSL_ACC_GYRO_OUTX_L_G  	0X22
#define LSM6DSL_ACC_GYRO_OUTX_H_G  	0X23
#define LSM6DSL_ACC_GYRO_OUTY_L_G  	0X24
#define LSM6DSL_ACC_GYRO_OUTY_H_G  	0X25
#define LSM6DSL_ACC_GYRO_OUTZ_L_G  	0X26
#define LSM6DSL_ACC_GYRO_OUTZ_H_G  	0X27
#define LSM6DSL_ACC_GYRO_OUTX_L_XL  	0X28
#define LSM6DSL_ACC_GYRO_OUTX_H_XL  	0X29
#define LSM6DSL_ACC_GYRO_OUTY_L_XL  	0X2A
#define LSM6DSL_ACC_GYRO_OUTY_H_XL  	0X2B
#define LSM6DSL_ACC_GYRO_OUTZ_L_XL  	0X2C
#define LSM6DSL_ACC_GYRO_OUTZ_H_XL  	0X2D
#define LSM6DSL_ACC_GYRO_SENSORHUB1_REG  	0X2E
#define LSM6DSL_ACC_GYRO_SENSORHUB2_REG  	0X2F
#define LSM6DSL_ACC_GYRO_SENSORHUB3_REG  	0X30
#define LSM6DSL_ACC_GYRO_SENSORHUB4_REG  	0X31
#define LSM6DSL_ACC_GYRO_SENSORHUB5_REG  	0X32
#define LSM6DSL_ACC_GYRO_SENSORHUB6_REG  	0X33
#define LSM6DSL_ACC_GYRO_SENSORHUB7_REG  	0X34
#define LSM6DSL_ACC_GYRO_SENSORHUB8_REG  	0X35
#define LSM6DSL_ACC_GYRO_SENSORHUB9_REG  	0X36
#define LSM6DSL_ACC_GYRO_SENSORHUB10_REG  	0X37
#define LSM6DSL_ACC_GYRO_SENSORHUB11_REG  	0X38
#define LSM6DSL_ACC_GYRO_SENSORHUB12_REG  	0X39
#define LSM6DSL_ACC_GYRO_FIFO_STATUS1  	0X3A
#define LSM6DSL_ACC_GYRO_FIFO_STATUS2  	0X3B
#define LSM6DSL_ACC_GYRO_FIFO_STATUS3  	0X3C
#define LSM6DSL_ACC_GYRO_FIFO_STATUS4  	0X3D
#define LSM6DSL_ACC_GYRO_FIFO_DATA_OUT_L  	0X3E
#define LSM6DSL_ACC_GYRO_FIFO_DATA_OUT_H  	0X3F
#define LSM6DSL_ACC_GYRO_TIMESTAMP0_REG  	0X40
#define LSM6DSL_ACC_GYRO_TIMESTAMP1_REG  	0X41
#define LSM6DSL_ACC_GYRO_TIMESTAMP2_REG  	0X42

#define LSM6DSL_ACC_GYRO_TIMESTAMP_L  	0X49
#define LSM6DSL_ACC_GYRO_TIMESTAMP_H  	0X4A

#define LSM6DSL_ACC_GYRO_STEP_COUNTER_L  	0X4B
#define LSM6DSL_ACC_GYRO_STEP_COUNTER_H  	0X4C

#define LSM6DSL_ACC_GYRO_SENSORHUB13_REG  	0X4D
#define LSM6DSL_ACC_GYRO_SENSORHUB14_REG  	0X4E
#define LSM6DSL_ACC_GYRO_SENSORHUB15_REG  	0X4F
#define LSM6DSL_ACC_GYRO_SENSORHUB16_REG  	0X50
#define LSM6DSL_ACC_GYRO_SENSORHUB17_REG  	0X51
#define LSM6DSL_ACC_GYRO_SENSORHUB18_REG  	0X52

#define LSM6DSL_ACC_GYRO_FUNC_SRC  	0X53
#define LSM6DSL_ACC_GYRO_TAP_CFG1  	0X58
#define LSM6DSL_ACC_GYRO_TAP_THS_6D  	0X59
#define LSM6DSL_ACC_GYRO_INT_DUR2  	0X5A
#define LSM6DSL_ACC_GYRO_WAKE_UP_THS  	0X5B
#define LSM6DSL_ACC_GYRO_WAKE_UP_DUR  	0X5C
#define LSM6DSL_ACC_GYRO_FREE_FALL  	0X5D
#define LSM6DSL_ACC_GYRO_MD1_CFG  	0X5E
#define LSM6DSL_ACC_GYRO_MD2_CFG  	0X5F

#define LSM6DSL_ACC_GYRO_OUT_MAG_RAW_X_L  	0X66
#define LSM6DSL_ACC_GYRO_OUT_MAG_RAW_X_H  	0X67
#define LSM6DSL_ACC_GYRO_OUT_MAG_RAW_Y_L  	0X68
#define LSM6DSL_ACC_GYRO_OUT_MAG_RAW_Y_H  	0X69
#define LSM6DSL_ACC_GYRO_OUT_MAG_RAW_Z_L  	0X6A
#define LSM6DSL_ACC_GYRO_OUT_MAG_RAW_Z_H  	0X6B

#define LSM6DSL_ACC_GYRO_X_OFS_USR  	0X73
#define LSM6DSL_ACC_GYRO_Y_OFS_USR  	0X74
#define LSM6DSL_ACC_GYRO_Z_OFS_USR  	0X75

/************** Embedded functions register mapping  *******************/
#define LSM6DSL_ACC_GYRO_SLV0_ADD                     0x02
#define LSM6DSL_ACC_GYRO_SLV0_SUBADD                  0x03
#define LSM6DSL_ACC_GYRO_SLAVE0_CONFIG                0x04
#define LSM6DSL_ACC_GYRO_SLV1_ADD                     0x05
#define LSM6DSL_ACC_GYRO_SLV1_SUBADD                  0x06
#define LSM6DSL_ACC_GYRO_SLAVE1_CONFIG                0x07
#define LSM6DSL_ACC_GYRO_SLV2_ADD                     0x08
#define LSM6DSL_ACC_GYRO_SLV2_SUBADD                  0x09
#define LSM6DSL_ACC_GYRO_SLAVE2_CONFIG                0x0A
#define LSM6DSL_ACC_GYRO_SLV3_ADD                     0x0B
#define LSM6DSL_ACC_GYRO_SLV3_SUBADD                  0x0C
#define LSM6DSL_ACC_GYRO_SLAVE3_CONFIG                0x0D
#define LSM6DSL_ACC_GYRO_DATAWRITE_SRC_MODE_SUB_SLV0  0x0E
#define LSM6DSL_ACC_GYRO_CONFIG_PEDO_THS_MIN          0x0F

#define LSM6DSL_ACC_GYRO_SM_STEP_THS                  0x13
#define LSM6DSL_ACC_GYRO_PEDO_DEB_REG                0x14
#define LSM6DSL_ACC_GYRO_STEP_COUNT_DELTA            0x15

#define LSM6DSL_ACC_GYRO_MAG_SI_XX                    0x24
#define LSM6DSL_ACC_GYRO_MAG_SI_XY                    0x25
#define LSM6DSL_ACC_GYRO_MAG_SI_XZ                    0x26
#define LSM6DSL_ACC_GYRO_MAG_SI_YX                    0x27
#define LSM6DSL_ACC_GYRO_MAG_SI_YY                    0x28
#define LSM6DSL_ACC_GYRO_MAG_SI_YZ                    0x29
#define LSM6DSL_ACC_GYRO_MAG_SI_ZX                    0x2A
#define LSM6DSL_ACC_GYRO_MAG_SI_ZY                    0x2B
#define LSM6DSL_ACC_GYRO_MAG_SI_ZZ                    0x2C
#define LSM6DSL_ACC_GYRO_MAG_OFFX_L                   0x2D
#define LSM6DSL_ACC_GYRO_MAG_OFFX_H                   0x2E
#define LSM6DSL_ACC_GYRO_MAG_OFFY_L                   0x2F
#define LSM6DSL_ACC_GYRO_MAG_OFFY_H                   0x30
#define LSM6DSL_ACC_GYRO_MAG_OFFZ_L                   0x31
#define LSM6DSL_ACC_GYRO_MAG_OFFZ_H                   0x32

#define LSM6DSL_ACC_GYRO_WHO_AM_I_BIT_MASK  	0xFF
#define LSM6DSL_ACC_GYRO_WHO_AM_I_BIT_POSITION  	0

#define LSM6DSL_ACC_GYRO_BDU_MASK  	0x40
typedef enum {
  	LSM6DSL_ACC_GYRO_BDU_CONTINUOS = 0x00,
  	LSM6DSL_ACC_GYRO_BDU_BLOCK_UPDATE = 0x40,
} LSM6DSL_ACC_GYRO_BDU_t;

#define LSM6DSL_ACC_GYRO_FS_XL_MASK  	0x0C
typedef enum {
  	LSM6DSL_ACC_GYRO_FS_XL_2g = 0x00,
  	LSM6DSL_ACC_GYRO_FS_XL_16g = 0x04,
  	LSM6DSL_ACC_GYRO_FS_XL_4g = 0x08,
  	LSM6DSL_ACC_GYRO_FS_XL_8g = 0x0C,
} LSM6DSL_ACC_GYRO_FS_XL_t;

#define LSM6DSL_ACC_GYRO_ODR_XL_MASK  	0xF0
typedef enum {
  	LSM6DSL_ACC_GYRO_ODR_XL_POWER_DOWN = 0x00,
  	LSM6DSL_ACC_GYRO_ODR_XL_13Hz = 0x10,
  	LSM6DSL_ACC_GYRO_ODR_XL_26Hz = 0x20,
  	LSM6DSL_ACC_GYRO_ODR_XL_52Hz = 0x30,
  	LSM6DSL_ACC_GYRO_ODR_XL_104Hz = 0x40,
  	LSM6DSL_ACC_GYRO_ODR_XL_208Hz = 0x50,
  	LSM6DSL_ACC_GYRO_ODR_XL_416Hz = 0x60,
  	LSM6DSL_ACC_GYRO_ODR_XL_833Hz = 0x70,
  	LSM6DSL_ACC_GYRO_ODR_XL_1660Hz = 0x80,
  	LSM6DSL_ACC_GYRO_ODR_XL_3330Hz = 0x90,
  	LSM6DSL_ACC_GYRO_ODR_XL_6660Hz = 0xA0,
} LSM6DSL_ACC_GYRO_ODR_XL_t;

#define LSM6DSL_ACC_GYRO_FS_G_MASK  	0x0C
typedef enum {
  	LSM6DSL_ACC_GYRO_FS_G_245dps = 0x00,
  	LSM6DSL_ACC_GYRO_FS_G_500dps = 0x04,
  	LSM6DSL_ACC_GYRO_FS_G_1000dps = 0x08,
  	LSM6DSL_ACC_GYRO_FS_G_2000dps = 0x0C,
} LSM6DSL_ACC_GYRO_FS_G_t;

#define LSM6DSL_ACC_GYRO_ODR_G_MASK  	0xF0
typedef enum {
  	LSM6DSL_ACC_GYRO_ODR_G_POWER_DOWN = 0x00,
  	LSM6DSL_ACC_GYRO_ODR_G_13Hz = 0x10,
  	LSM6DSL_ACC_GYRO_ODR_G_26Hz = 0x20,
  	LSM6DSL_ACC_GYRO_ODR_G_52Hz = 0x30,
  	LSM6DSL_ACC_GYRO_ODR_G_104Hz = 0x40,
  	LSM6DSL_ACC_GYRO_ODR_G_208Hz = 0x50,
  	LSM6DSL_ACC_GYRO_ODR_G_416Hz = 0x60,
  	LSM6DSL_ACC_GYRO_ODR_G_833Hz = 0x70,
  	LSM6DSL_ACC_GYRO_ODR_G_1660Hz = 0x80,
  	LSM6DSL_ACC_GYRO_ODR_G_3330Hz = 0x90,
  	LSM6DSL_ACC_GYRO_ODR_G_6660Hz = 0xA0,
} LSM6DSL_ACC_GYRO_ODR_G_t;

#define LSM6DSL_ACC_GYRO_BW_SEL_MASK  	0x02
typedef enum {
  	LSM6DSL_ACC_GYRO_BW_SEL_ODR2 = 0x00,
  	LSM6DSL_ACC_GYRO_BW_SEL_ODR4 = 0x02,
} LSM6DSL_ACC_GYRO_BW_SEL_t;

#define LSM6DSL_ACC_GYRO_FS_125_MASK  	0x02
typedef enum {
  	LSM6DSL_ACC_GYRO_FS_125_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_FS_125_ENABLED = 0x02,
} LSM6DSL_ACC_GYRO_FS_125_t;

#define LSM6DSL_ACC_GYRO_BLE_MASK  	0x02
typedef enum {
  	LSM6DSL_ACC_GYRO_BLE_LSB = 0x00,
  	LSM6DSL_ACC_GYRO_BLE_MSB = 0x02,
} LSM6DSL_ACC_GYRO_BLE_t;

#define LSM6DSL_ACC_GYRO_EMB_ACC_MASK  	0x80
typedef enum {
  	LSM6DSL_ACC_GYRO_EMBEDDED_ACCESS_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_EMBEDDED_ACCESS_ENABLED = 0x80,
} LSM6DSL_ACC_GYRO_EMB_ACC_t;

#define LSM6DSL_ACC_GYRO_TPH_MASK  	0xFF
#define LSM6DSL_ACC_GYRO_TPH_POSITION  	0

#define LSM6DSL_ACC_GYRO_SYNC_RES_RATIO_MASK  	0x03
typedef enum {
  	LSM6DSL_ACC_GYRO_TIM_RATIO_2_11 = 0x00,
  	LSM6DSL_ACC_GYRO_TIM_RATIO_2_12 = 0x01,
  	LSM6DSL_ACC_GYRO_TIM_RATIO_2_13 = 0x02,
  	LSM6DSL_ACC_GYRO_TIM_RATIO_2_14 = 0x03,
} LSM6DSL_ACC_GYRO_SYNC_RES_RATIO_t;

#define LSM6DSL_ACC_GYRO_WTM_FIFO_CTRL1_MASK  	0xFF
#define LSM6DSL_ACC_GYRO_WTM_FIFO_CTRL1_POSITION  	0
#define LSM6DSL_ACC_GYRO_WTM_FIFO_CTRL2_MASK  	0x07
#define LSM6DSL_ACC_GYRO_WTM_FIFO_CTRL2_POSITION  	0

#define LSM6DSL_ACC_GYRO_FIFO_TEMP_MASK  	0x08
typedef enum {
  	LSM6DSL_ACC_GYRO_FIFO_TEMP_DISABLE = 0x00,
  	LSM6DSL_ACC_GYRO_FIFO_TEMP_ENABLE = 0x08,
} LSM6DSL_ACC_GYRO_FIFO_TEMP_t;

#define LSM6DSL_ACC_GYRO_TIM_PEDO_FIFO_DRDY_MASK  	0x40
typedef enum {
  	LSM6DSL_ACC_GYRO_TIM_PEDO_FIFO_DRDY_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_TIM_PEDO_FIFO_DRDY_ENABLED = 0x40,
} LSM6DSL_ACC_GYRO_TIM_PEDO_FIFO_DRDY_t;

#define LSM6DSL_ACC_GYRO_TIM_PEDO_FIFO_EN_MASK  	0x80
typedef enum {
  	LSM6DSL_ACC_GYRO_TIM_PEDO_FIFO_EN_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_TIM_PEDO_FIFO_EN_ENABLED = 0x80,
} LSM6DSL_ACC_GYRO_TIM_PEDO_FIFO_EN_t;

#define LSM6DSL_ACC_GYRO_DEC_FIFO_XL_MASK  	0x07
typedef enum {
  	LSM6DSL_ACC_GYRO_DEC_FIFO_XL_DATA_NOT_IN_FIFO = 0x00,
  	LSM6DSL_ACC_GYRO_DEC_FIFO_XL_NO_DECIMATION = 0x01,
  	LSM6DSL_ACC_GYRO_DEC_FIFO_XL_DECIMATION_BY_2 = 0x02,
  	LSM6DSL_ACC_GYRO_DEC_FIFO_XL_DECIMATION_BY_3 = 0x03,
  	LSM6DSL_ACC_GYRO_DEC_FIFO_XL_DECIMATION_BY_4 = 0x04,
  	LSM6DSL_ACC_GYRO_DEC_FIFO_XL_DECIMATION_BY_8 = 0x05,
  	LSM6DSL_ACC_GYRO_DEC_FIFO_XL_DECIMATION_BY_16 = 0x06,
  	LSM6DSL_ACC_GYRO_DEC_FIFO_XL_DECIMATION_BY_32 = 0x07,
} LSM6DSL_ACC_GYRO_DEC_FIFO_XL_t;

#define LSM6DSL_ACC_GYRO_DEC_FIFO_G_MASK  	0x38
typedef enum {
  	LSM6DSL_ACC_GYRO_DEC_FIFO_G_DATA_NOT_IN_FIFO = 0x00,
  	LSM6DSL_ACC_GYRO_DEC_FIFO_G_NO_DECIMATION = 0x08,
  	LSM6DSL_ACC_GYRO_DEC_FIFO_G_DECIMATION_BY_2 = 0x10,
  	LSM6DSL_ACC_GYRO_DEC_FIFO_G_DECIMATION_BY_3 = 0x18,
  	LSM6DSL_ACC_GYRO_DEC_FIFO_G_DECIMATION_BY_4 = 0x20,
  	LSM6DSL_ACC_GYRO_DEC_FIFO_G_DECIMATION_BY_8 = 0x28,
  	LSM6DSL_ACC_GYRO_DEC_FIFO_G_DECIMATION_BY_16 = 0x30,
  	LSM6DSL_ACC_GYRO_DEC_FIFO_G_DECIMATION_BY_32 = 0x38,
} LSM6DSL_ACC_GYRO_DEC_FIFO_G_t;

#define LSM6DSL_ACC_GYRO_DEC_FIFO_DS3_MASK  	0x07
typedef enum {
  	LSM6DSL_ACC_GYRO_DEC_FIFO_DS3_DATA_NOT_IN_FIFO = 0x00,
  	LSM6DSL_ACC_GYRO_DEC_FIFO_DS3_NO_DECIMATION = 0x01,
  	LSM6DSL_ACC_GYRO_DEC_FIFO_DS3_DECIMATION_BY_2 = 0x02,
  	LSM6DSL_ACC_GYRO_DEC_FIFO_DS3_DECIMATION_BY_3 = 0x03,
  	LSM6DSL_ACC_GYRO_DEC_FIFO_DS3_DECIMATION_BY_4 = 0x04,
  	LSM6DSL_ACC_GYRO_DEC_FIFO_DS3_DECIMATION_BY_8 = 0x05,
  	LSM6DSL_ACC_GYRO_DEC_FIFO_DS3_DECIMATION_BY_16 = 0x06,
  	LSM6DSL_ACC_GYRO_DEC_FIFO_DS3_DECIMATION_BY_32 = 0x07,
} LSM6DSL_ACC_GYRO_DEC_FIFO_DS3_t;

#define LSM6DSL_ACC_GYRO_DEC_FIFO_DS4_MASK  	0x38
typedef enum {
  	LSM6DSL_ACC_GYRO_DEC_FIFO_DS4_DATA_NOT_IN_FIFO = 0x00,
  	LSM6DSL_ACC_GYRO_DEC_FIFO_DS4_NO_DECIMATION = 0x08,
  	LSM6DSL_ACC_GYRO_DEC_FIFO_DS4_DECIMATION_BY_2 = 0x10,
  	LSM6DSL_ACC_GYRO_DEC_FIFO_DS4_DECIMATION_BY_3 = 0x18,
  	LSM6DSL_ACC_GYRO_DEC_FIFO_DS4_DECIMATION_BY_4 = 0x20,
  	LSM6DSL_ACC_GYRO_DEC_FIFO_DS4_DECIMATION_BY_8 = 0x28,
  	LSM6DSL_ACC_GYRO_DEC_FIFO_DS4_DECIMATION_BY_16 = 0x30,
  	LSM6DSL_ACC_GYRO_DEC_FIFO_DS4_DECIMATION_BY_32 = 0x38,
} LSM6DSL_ACC_GYRO_DEC_FIFO_DS4_t;

#define LSM6DSL_ACC_GYRO_HI_DATA_ONLY_MASK  	0x40
typedef enum {
  	LSM6DSL_ACC_GYRO_HI_DATA_ONLY_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_HI_DATA_ONLY_ENABLED = 0x40,
} LSM6DSL_ACC_GYRO_HI_DATA_ONLY_t;

#define LSM6DSL_ACC_GYRO_STOP_ON_FTH_MASK  	0x80
typedef enum {
  	LSM6DSL_ACC_GYRO_STOP_ON_FTH_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_STOP_ON_FTH_ENABLED = 0x80,
} LSM6DSL_ACC_GYRO_STOP_ON_FTH_t;

#define LSM6DSL_ACC_GYRO_FIFO_MODE_MASK  	0x07
typedef enum {
  	LSM6DSL_ACC_GYRO_FIFO_MODE_BYPASS = 0x00,
  	LSM6DSL_ACC_GYRO_FIFO_MODE_FIFO = 0x01,
  	LSM6DSL_ACC_GYRO_FIFO_MODE_STREAM = 0x02,
  	LSM6DSL_ACC_GYRO_FIFO_MODE_STF = 0x03,
  	LSM6DSL_ACC_GYRO_FIFO_MODE_BTS = 0x04,
  	LSM6DSL_ACC_GYRO_FIFO_MODE_DYN_STREAM = 0x05,
  	LSM6DSL_ACC_GYRO_FIFO_MODE_DYN_STREAM_2 = 0x06,
  	LSM6DSL_ACC_GYRO_FIFO_MODE_BTF = 0x07,
} LSM6DSL_ACC_GYRO_FIFO_MODE_t;

#define LSM6DSL_ACC_GYRO_ODR_FIFO_MASK  	0x78
typedef enum {
  	LSM6DSL_ACC_GYRO_ODR_FIFO_10Hz = 0x08,
  	LSM6DSL_ACC_GYRO_ODR_FIFO_25Hz = 0x10,
  	LSM6DSL_ACC_GYRO_ODR_FIFO_50Hz = 0x18,
  	LSM6DSL_ACC_GYRO_ODR_FIFO_100Hz = 0x20,
  	LSM6DSL_ACC_GYRO_ODR_FIFO_200Hz = 0x28,
  	LSM6DSL_ACC_GYRO_ODR_FIFO_400Hz = 0x30,
  	LSM6DSL_ACC_GYRO_ODR_FIFO_800Hz = 0x38,
  	LSM6DSL_ACC_GYRO_ODR_FIFO_1600Hz = 0x40,
  	LSM6DSL_ACC_GYRO_ODR_FIFO_3300Hz = 0x48,
  	LSM6DSL_ACC_GYRO_ODR_FIFO_6600Hz = 0x50,
  	LSM6DSL_ACC_GYRO_ODR_FIFO_13300Hz = 0x58,
} LSM6DSL_ACC_GYRO_ODR_FIFO_t;

#define LSM6DSL_ACC_GYRO_DRDY_PULSE_MASK  	0x80
typedef enum {
  	LSM6DSL_ACC_GYRO_DRDY_LATCH = 0x00,
  	LSM6DSL_ACC_GYRO_DRDY_PULSE = 0x80,
} LSM6DSL_ACC_GYRO_DRDY_PULSE_t;

#define LSM6DSL_ACC_GYRO_INT1_DRDY_XL_MASK  	0x01
typedef enum {
  	LSM6DSL_ACC_GYRO_INT1_DRDY_XL_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_INT1_DRDY_XL_ENABLED = 0x01,
} LSM6DSL_ACC_GYRO_INT1_DRDY_XL_t;

#define LSM6DSL_ACC_GYRO_INT1_DRDY_G_MASK  	0x02
typedef enum {
  	LSM6DSL_ACC_GYRO_INT1_DRDY_G_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_INT1_DRDY_G_ENABLED = 0x02,
} LSM6DSL_ACC_GYRO_INT1_DRDY_G_t;

#define LSM6DSL_ACC_GYRO_INT1_BOOT_MASK  	0x04
typedef enum {
  	LSM6DSL_ACC_GYRO_INT1_BOOT_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_INT1_BOOT_ENABLED = 0x04,
} LSM6DSL_ACC_GYRO_INT1_BOOT_t;

#define LSM6DSL_ACC_GYRO_INT1_FTH_MASK  	0x08
typedef enum {
  	LSM6DSL_ACC_GYRO_INT1_FTH_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_INT1_FTH_ENABLED = 0x08,
} LSM6DSL_ACC_GYRO_INT1_FTH_t;

#define LSM6DSL_ACC_GYRO_INT1_OVR_MASK  	0x10
typedef enum {
  	LSM6DSL_ACC_GYRO_INT1_OVR_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_INT1_OVR_ENABLED = 0x10,
} LSM6DSL_ACC_GYRO_INT1_OVR_t;

#define LSM6DSL_ACC_GYRO_INT1_FULL_FLAG_MASK  	0x20
typedef enum {
  	LSM6DSL_ACC_GYRO_INT1_FULL_FLAG_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_INT1_FULL_FLAG_ENABLED = 0x20,
} LSM6DSL_ACC_GYRO_INT1_FULL_FLAG_t;

#define LSM6DSL_ACC_GYRO_INT1_SIGN_MOT_MASK  	0x40
typedef enum {
  	LSM6DSL_ACC_GYRO_INT1_SIGN_MOT_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_INT1_SIGN_MOT_ENABLED = 0x40,
} LSM6DSL_ACC_GYRO_INT1_SIGN_MOT_t;

#define LSM6DSL_ACC_GYRO_INT1_PEDO_MASK  	0x80
typedef enum {
  	LSM6DSL_ACC_GYRO_INT1_PEDO_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_INT1_PEDO_ENABLED = 0x80,
} LSM6DSL_ACC_GYRO_INT1_PEDO_t;

#define LSM6DSL_ACC_GYRO_INT2_DRDY_XL_MASK  	0x01
typedef enum {
  	LSM6DSL_ACC_GYRO_INT2_DRDY_XL_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_INT2_DRDY_XL_ENABLED = 0x01,
} LSM6DSL_ACC_GYRO_INT2_DRDY_XL_t;

#define LSM6DSL_ACC_GYRO_INT2_DRDY_G_MASK  	0x02
typedef enum {
  	LSM6DSL_ACC_GYRO_INT2_DRDY_G_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_INT2_DRDY_G_ENABLED = 0x02,
} LSM6DSL_ACC_GYRO_INT2_DRDY_G_t;

#define LSM6DSL_ACC_GYRO_INT2_DRDY_TEMP_MASK  	0x04
typedef enum {
  	LSM6DSL_ACC_GYRO_INT2_DRDY_TEMP_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_INT2_DRDY_TEMP_ENABLED = 0x04,
} LSM6DSL_ACC_GYRO_INT2_DRDY_TEMP_t;

#define LSM6DSL_ACC_GYRO_INT2_FTH_MASK  	0x08
typedef enum {
  	LSM6DSL_ACC_GYRO_INT2_FTH_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_INT2_FTH_ENABLED = 0x08,
} LSM6DSL_ACC_GYRO_INT2_FTH_t;

#define LSM6DSL_ACC_GYRO_INT2_OVR_MASK  	0x10
typedef enum {
  	LSM6DSL_ACC_GYRO_INT2_OVR_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_INT2_OVR_ENABLED = 0x10,
} LSM6DSL_ACC_GYRO_INT2_OVR_t;

#define LSM6DSL_ACC_GYRO_INT2_FULL_FLAG_MASK  	0x20
typedef enum {
  	LSM6DSL_ACC_GYRO_INT2_FULL_FLAG_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_INT2_FULL_FLAG_ENABLED = 0x20,
} LSM6DSL_ACC_GYRO_INT2_FULL_FLAG_t;

#define LSM6DSL_ACC_GYRO_INT2_STEP_COUNT_OV_MASK  	0x40
typedef enum {
  	LSM6DSL_ACC_GYRO_INT2_STEP_COUNT_OV_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_INT2_STEP_COUNT_OV_ENABLED = 0x40,
} LSM6DSL_ACC_GYRO_INT2_STEP_COUNT_OV_t;

#define LSM6DSL_ACC_GYRO_INT2_STEP_DELTA_MASK  	0x80
typedef enum {
  	LSM6DSL_ACC_GYRO_INT2_STEP_DELTA_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_INT2_STEP_DELTA_ENABLED = 0x80,
} LSM6DSL_ACC_GYRO_INT2_STEP_DELTA_t;

#define LSM6DSL_ACC_GYRO_SW_RESET_MASK  	0x01
typedef enum {
  	LSM6DSL_ACC_GYRO_SW_RESET_NORMAL_MODE = 0x00,
  	LSM6DSL_ACC_GYRO_SW_RESET_RESET_DEVICE = 0x01,
} LSM6DSL_ACC_GYRO_SW_RESET_t;

#define LSM6DSL_ACC_GYRO_IF_INC_MASK  	0x04
typedef enum {
  	LSM6DSL_ACC_GYRO_IF_INC_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_IF_INC_ENABLED = 0x04,
} LSM6DSL_ACC_GYRO_IF_INC_t;

#define LSM6DSL_ACC_GYRO_SIM_MASK  	0x08
typedef enum {
  	LSM6DSL_ACC_GYRO_SIM_4_WIRE = 0x00,
  	LSM6DSL_ACC_GYRO_SIM_3_WIRE = 0x08,
} LSM6DSL_ACC_GYRO_SIM_t;

#define LSM6DSL_ACC_GYRO_PP_OD_MASK  	0x10
typedef enum {
  	LSM6DSL_ACC_GYRO_PP_OD_PUSH_PULL = 0x00,
  	LSM6DSL_ACC_GYRO_PP_OD_OPEN_DRAIN = 0x10,
} LSM6DSL_ACC_GYRO_PP_OD_t;

#define LSM6DSL_ACC_GYRO_INT_ACT_LEVEL_MASK  	0x20
typedef enum {
  	LSM6DSL_ACC_GYRO_INT_ACT_LEVEL_ACTIVE_HI = 0x00,
  	LSM6DSL_ACC_GYRO_INT_ACT_LEVEL_ACTIVE_LO = 0x20,
} LSM6DSL_ACC_GYRO_INT_ACT_LEVEL_t;

#define LSM6DSL_ACC_GYRO_BOOT_MASK  	0x80
typedef enum {
  	LSM6DSL_ACC_GYRO_BOOT_NORMAL_MODE = 0x00,
  	LSM6DSL_ACC_GYRO_BOOT_REBOOT_MODE = 0x80,
} LSM6DSL_ACC_GYRO_BOOT_t;

#define LSM6DSL_ACC_GYRO_LPF1_SEL_G_MASK  	0x02
typedef enum {
  	LSM6DSL_ACC_GYRO_MODE3_LPF1_G_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_MODE3_LPF1_G_ENABLED = 0x02,
} LSM6DSL_ACC_GYRO_LPF1_SEL_G_t;

#define LSM6DSL_ACC_GYRO_I2C_DISABLE_MASK  	0x04
typedef enum {
  	LSM6DSL_ACC_GYRO_I2C_DISABLE_I2C_AND_SPI = 0x00,
  	LSM6DSL_ACC_GYRO_I2C_DISABLE_SPI_ONLY = 0x04,
} LSM6DSL_ACC_GYRO_I2C_DISABLE_t;

#define LSM6DSL_ACC_GYRO_DRDY_MSK_MASK  	0x08
typedef enum {
  	LSM6DSL_ACC_GYRO_DRDY_MSK_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_DRDY_MSK_ENABLED = 0x08,
} LSM6DSL_ACC_GYRO_DRDY_MSK_t;

#define LSM6DSL_ACC_GYRO_INT2_ON_INT1_MASK  	0x20
typedef enum {
  	LSM6DSL_ACC_GYRO_INT2_ON_INT1_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_INT2_ON_INT1_ENABLED = 0x20,
} LSM6DSL_ACC_GYRO_INT2_ON_INT1_t;

#define LSM6DSL_ACC_GYRO_SLEEP_G_MASK  	0x40
typedef enum {
  	LSM6DSL_ACC_GYRO_SLEEP_G_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_SLEEP_G_ENABLED = 0x40,
} LSM6DSL_ACC_GYRO_SLEEP_G_t;

#define LSM6DSL_ACC_GYRO_ST_XL_MASK  	0x03
typedef enum {
  	LSM6DSL_ACC_GYRO_ST_XL_NORMAL_MODE = 0x00,
  	LSM6DSL_ACC_GYRO_ST_XL_POS_SIGN_TEST = 0x01,
  	LSM6DSL_ACC_GYRO_ST_XL_NEG_SIGN_TEST = 0x02,
  	LSM6DSL_ACC_GYRO_ST_XL_NA = 0x03,
} LSM6DSL_ACC_GYRO_ST_XL_t;

#define LSM6DSL_ACC_GYRO_ST_G_MASK  	0x0C
typedef enum {
  	LSM6DSL_ACC_GYRO_ST_G_NORMAL_MODE = 0x00,
  	LSM6DSL_ACC_GYRO_ST_G_POS_SIGN_TEST = 0x04,
  	LSM6DSL_ACC_GYRO_ST_G_NA = 0x08,
  	LSM6DSL_ACC_GYRO_ST_G_NEG_SIGN_TEST = 0x0C,
} LSM6DSL_ACC_GYRO_ST_G_t;

#define LSM6DSL_ACC_GYRO_DEN_LH_MASK  	0x10
typedef enum {
  	LSM6DSL_ACC_GYRO_DEN_LOW = 0x00,
  	LSM6DSL_ACC_GYRO_DEN_HIGH = 0x10,
} LSM6DSL_ACC_GYRO_DEN_LH_t;

#define LSM6DSL_ACC_GYRO_LSM6DSL_ACC_GYRO_ROUNDING_t_MASK  	0xE0
typedef enum {
  	LSM6DSL_ACC_GYRO_NO_ROUNDING = 0x00,
  	LSM6DSL_ACC_GYRO_ACC_ONLY = 0x20,
  	LSM6DSL_ACC_GYRO_GYRO_ONLY = 0x40,
	LSM6DSL_ACC_GYRO_ACC_GYRO = 0x60,
  	LSM6DSL_ACC_GYRO_SH1_SH6 = 0x80,
	LSM6DSL_ACC_GYRO_ACC_SH1_SH6 = 0xA0,
	LSM6DSL_ACC_GYRO_ACC_GYRO_SH1_SH6_SH7_SH12 = 0xC0,
	LSM6DSL_ACC_GYRO_ACC_GYRO_SH1_SH6	 =0xE0,
} LSM6DSL_ACC_GYRO_ROUNDING_t;

#define LSM6DSL_ACC_GYRO_FTYPE_MASK  	0x03
typedef enum {
  	LSM6DSL_ACC_GYRO_LP_G_NORMAL = 0x00,
  	LSM6DSL_ACC_GYRO_LP_G_NARROW = 0x01,
  	LSM6DSL_ACC_GYRO_LP_G_VERY_NARROW = 0x02,
  	LSM6DSL_ACC_GYRO_LP_G_WIDE = 0x03,
} LSM6DSL_ACC_GYRO_FTYPE_t;

#define LSM6DSL_ACC_GYRO_USR_OFF_W_MASK  	0x08
typedef enum {
  	LSM6DSL_ACC_GYRO_2Emin10 = 0x00,
  	LSM6DSL_ACC_GYRO_2Emin6 = 0x08,
} LSM6DSL_ACC_GYRO_USR_OFF_W_t;

#define LSM6DSL_ACC_GYRO_LP_XL_MASK  	0x10
typedef enum {
  	LSM6DSL_ACC_GYRO_LP_XL_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_LP_XL_ENABLED = 0x10,
} LSM6DSL_ACC_GYRO_LP_XL_t;

#define LSM6DSL_ACC_GYRO_DEN_LVL2_EN_MASK  	0x20
typedef enum {
  	LSM6DSL_ACC_GYRO_DEN_LVL2_EN_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_DEN_LVL2_EN_ENABLED = 0x20,
} LSM6DSL_ACC_GYRO_DEN_LVL2_EN_t;

#define LSM6DSL_ACC_GYRO_DEN_LVL_EN_MASK  	0x40
typedef enum {
  	LSM6DSL_ACC_GYRO_DEN_LVL_EN_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_DEN_LVL_EN_ENABLED = 0x40,
} LSM6DSL_ACC_GYRO_DEN_LVL_EN_t;

#define LSM6DSL_ACC_GYRO_DEN_EDGE_EN_MASK  	0x80
typedef enum {
  	LSM6DSL_ACC_GYRO_DEN_EDGE_EN_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_DEN_EDGE_EN_ENABLED = 0x80,
} LSM6DSL_ACC_GYRO_DEN_EDGE_EN_t;

#define LSM6DSL_ACC_GYRO_RND_STATUS_MASK  	0x04
typedef enum {
  	LSM6DSL_ACC_GYRO_RND_DISABLE = 0x00,
  	LSM6DSL_ACC_GYRO_RND_ENABLE  = 0x04,
} LSM6DSL_ACC_GYRO_RND_STATUS_t;

#define LSM6DSL_ACC_GYRO_HPM_G_MASK  	0x30
typedef enum {
  	LSM6DSL_ACC_GYRO_HPM_G_0Hz016 = 0x00,
  	LSM6DSL_ACC_GYRO_HPM_G_0Hz065  = 0x10,
  	LSM6DSL_ACC_GYRO_HPM_G_2Hz260 = 0x20,
  	LSM6DSL_ACC_GYRO_HPM_G_1Hz04 = 0x30,
} LSM6DSL_ACC_GYRO_HPM_G_t;

#define LSM6DSL_ACC_GYRO_HP_EN_MASK  	0x40
typedef enum {
  	LSM6DSL_ACC_GYRO_HP_EN_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_HP_EN_ENABLED = 0x40,
} LSM6DSL_ACC_GYRO_HP_EN_t;

#define LSM6DSL_ACC_GYRO_LP_EN_MASK  	0x80
typedef enum {
  	LSM6DSL_ACC_GYRO_LP_EN_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_LP_EN_ENABLED = 0x80,
} LSM6DSL_ACC_GYRO_LP_EN_t;

#define LSM6DSL_ACC_GYRO_ROUNDING_STATUS_MASK  	0x04
typedef enum {
  	LSM6DSL_ACC_GYRO_ROUNDING_STATUS_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_ROUNDING_STATUS_ENABLED = 0x04,
} LSM6DSL_ACC_GYRO_ROUNDING_STATUS_t;

#define LSM6DSL_ACC_GYRO_HP_G_RST_MASK  	0x08
typedef enum {
  	LSM6DSL_ACC_GYRO_HP_G_RST_OFF = 0x00,
  	LSM6DSL_ACC_GYRO_HP_G_RST_ON = 0x08,
} LSM6DSL_ACC_GYRO_HP_G_RST_t;

#define LSM6DSL_ACC_GYRO_LOW_PASS_ON_6D_MASK  	0x01
typedef enum {
  	LSM6DSL_ACC_GYRO_LOW_PASS_ON_6D_OFF = 0x00,
  	LSM6DSL_ACC_GYRO_LOW_PASS_ON_6D_ON = 0x01,
} LSM6DSL_ACC_GYRO_LOW_PASS_ON_6D_t;

#define LSM6DSL_ACC_GYRO_HP_SLOPE_XL_MASK  	0x04
typedef enum {
  	LSM6DSL_ACC_GYRO_HP_SLOPE_XL_EN = 0x00,
  	LSM6DSL_ACC_GYRO_HP_SLOPE_XL_DIS = 0x04,
} LSM6DSL_ACC_GYRO_HP_SLOPE_XL_t;

#define LSM6DSL_ACC_GYRO_IN_COMP_MASK  	0x80
typedef enum {
  	LSM6DSL_ACC_GYRO_IN_ODR_DIV_2 = 0x00,
  	LSM6DSL_ACC_GYRO_IN_ODR_DIV_4 = 0x80,
} LSM6DSL_ACC_GYRO_IN_COMP_t;

#define LSM6DSL_ACC_GYRO_HP_REF_MODE_MASK  	0x10
typedef enum {
  	LSM6DSL_ACC_GYRO_HP_REF_DISABLE = 0x00,
  	LSM6DSL_ACC_GYRO_HP_REF_ENABLE = 0x10,
} LSM6DSL_ACC_GYRO_HP_REF_MODE_t;

#define LSM6DSL_ACC_GYRO_HPCF_XL_MASK  	0x60
typedef enum {
  	LSM6DSL_ACC_GYRO_HPCF_XL_DIV4 = 0x00,
  	LSM6DSL_ACC_GYRO_HPCF_XL_DIV100 = 0x20,
  	LSM6DSL_ACC_GYRO_HPCF_XL_DIV9 = 0x40,
  	LSM6DSL_ACC_GYRO_HPCF_XL_DIV400 = 0x60,
} LSM6DSL_ACC_GYRO_HPCF_XL_t;

#define LSM6DSL_ACC_GYRO_LPF2_XL_MASK  	0x80
typedef enum {
  	LSM6DSL_ACC_GYRO_LPF2_XL_DISABLE = 0x00,
  	LSM6DSL_ACC_GYRO_LPF2_XL_ENABLE = 0x80,
} LSM6DSL_ACC_GYRO_LPF2_XL_t;

#define LSM6DSL_ACC_GYRO_SOFT_MASK  	0x04
typedef enum {
  	LSM6DSL_ACC_GYRO_SOFT_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_SOFT_ENABLE = 0x04,
} LSM6DSL_ACC_GYRO_SOFT_t;

#define LSM6DSL_ACC_GYRO_SIGN_MOTION_EN_MASK  	0x01
typedef enum {
  	LSM6DSL_ACC_GYRO_SIGN_MOTION_EN_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_SIGN_MOTION_EN_ENABLED = 0x01,
} LSM6DSL_ACC_GYRO_SIGN_MOTION_EN_t;

#define LSM6DSL_ACC_GYRO_PEDO_RST_STEP_MASK  	0x02
typedef enum {
  	LSM6DSL_ACC_GYRO_PEDO_RST_STEP_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_PEDO_RST_STEP_ENABLED = 0x02,
} LSM6DSL_ACC_GYRO_PEDO_RST_STEP_t;

#define LSM6DSL_ACC_GYRO_FUNC_EN_MASK  	0x04
typedef enum {
  	LSM6DSL_ACC_GYRO_FUNC_EN_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_FUNC_EN_ENABLED = 0x04,
} LSM6DSL_ACC_GYRO_FUNC_EN_t;

#define LSM6DSL_ACC_GYRO_TILT_MASK  	0x08
typedef enum {
  	LSM6DSL_ACC_GYRO_TILT_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_TILT_ENABLED = 0x08,
} LSM6DSL_ACC_GYRO_TILT_G_t;

#define LSM6DSL_ACC_GYRO_PEDO_MASK  	0x10
typedef enum {
  	LSM6DSL_ACC_GYRO_PEDO_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_PEDO_ENABLED = 0x10,
} LSM6DSL_ACC_GYRO_PEDO_t;

#define LSM6DSL_ACC_GYRO_TIMER_MASK  	0x20
typedef enum {
  	LSM6DSL_ACC_GYRO_TIMER_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_TIMER_ENABLED = 0x20,
} LSM6DSL_ACC_GYRO_TIMER_t;

#define LSM6DSL_ACC_GYRO_MASTER_ON_MASK  	0x01
typedef enum {
  	LSM6DSL_ACC_GYRO_MASTER_ON_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_MASTER_ON_ENABLED = 0x01,
} LSM6DSL_ACC_GYRO_MASTER_ON_t;

#define LSM6DSL_ACC_GYRO_IRON_EN_MASK  	0x02
typedef enum {
  	LSM6DSL_ACC_GYRO_IRON_EN_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_IRON_EN_ENABLED = 0x02,
} LSM6DSL_ACC_GYRO_IRON_EN_t;

#define LSM6DSL_ACC_GYRO_PASS_THRU_MODE_MASK  	0x04
typedef enum {
  	LSM6DSL_ACC_GYRO_PASS_THRU_MODE_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_PASS_THRU_MODE_ENABLED = 0x04,
} LSM6DSL_ACC_GYRO_PASS_THRU_MODE_t;

#define LSM6DSL_ACC_GYRO_PULL_UP_EN_MASK  	0x08
typedef enum {
  	LSM6DSL_ACC_GYRO_PULL_UP_EN_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_PULL_UP_EN_ENABLED = 0x08,
} LSM6DSL_ACC_GYRO_PULL_UP_EN_t;

#define LSM6DSL_ACC_GYRO_START_CONFIG_MASK  	0x10
typedef enum {
  	LSM6DSL_ACC_GYRO_START_CONFIG_XL_G_DRDY = 0x00,
  	LSM6DSL_ACC_GYRO_START_CONFIG_EXT_INT2 = 0x10,
} LSM6DSL_ACC_GYRO_START_CONFIG_t;

#define LSM6DSL_ACC_GYRO_DATA_VAL_SEL_FIFO_MASK  	0x40
typedef enum {
  	LSM6DSL_ACC_GYRO_DATA_VAL_SEL_FIFO_XL_G_DRDY = 0x00,
  	LSM6DSL_ACC_GYRO_DATA_VAL_SEL_FIFO_SHUB_DRDY = 0x40,
} LSM6DSL_ACC_GYRO_DATA_VAL_SEL_FIFO_t;

#define LSM6DSL_ACC_GYRO_DRDY_ON_INT1_MASK  	0x80
typedef enum {
  	LSM6DSL_ACC_GYRO_DRDY_ON_INT1_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_DRDY_ON_INT1_ENABLED = 0x80,
} LSM6DSL_ACC_GYRO_DRDY_ON_INT1_t;

#define LSM6DSL_ACC_GYRO_Z_WU_MASK  	0x01
typedef enum {
  	LSM6DSL_ACC_GYRO_Z_WU_NOT_DETECTED = 0x00,
  	LSM6DSL_ACC_GYRO_Z_WU_DETECTED = 0x01,
} LSM6DSL_ACC_GYRO_Z_WU_t;

#define LSM6DSL_ACC_GYRO_Y_WU_MASK  	0x02
typedef enum {
  	LSM6DSL_ACC_GYRO_Y_WU_NOT_DETECTED = 0x00,
  	LSM6DSL_ACC_GYRO_Y_WU_DETECTED = 0x02,
} LSM6DSL_ACC_GYRO_Y_WU_t;

#define LSM6DSL_ACC_GYRO_X_WU_MASK  	0x04
typedef enum {
  	LSM6DSL_ACC_GYRO_X_WU_NOT_DETECTED = 0x00,
  	LSM6DSL_ACC_GYRO_X_WU_DETECTED = 0x04,
} LSM6DSL_ACC_GYRO_X_WU_t;

#define LSM6DSL_ACC_GYRO_WU_EV_STATUS_MASK  	0x08
typedef enum {
  	LSM6DSL_ACC_GYRO_WU_EV_STATUS_NOT_DETECTED = 0x00,
  	LSM6DSL_ACC_GYRO_WU_EV_STATUS_DETECTED = 0x08,
} LSM6DSL_ACC_GYRO_WU_EV_STATUS_t;

#define LSM6DSL_ACC_GYRO_SLEEP_EV_STATUS_MASK  	0x10
typedef enum {
  	LSM6DSL_ACC_GYRO_SLEEP_EV_STATUS_NOT_DETECTED = 0x00,
  	LSM6DSL_ACC_GYRO_SLEEP_EV_STATUS_DETECTED = 0x10,
} LSM6DSL_ACC_GYRO_SLEEP_EV_STATUS_t;

#define LSM6DSL_ACC_GYRO_FF_EV_STATUS_MASK  	0x20
typedef enum {
  	LSM6DSL_ACC_GYRO_FF_EV_STATUS_NOT_DETECTED = 0x00,
  	LSM6DSL_ACC_GYRO_FF_EV_STATUS_DETECTED = 0x20,
} LSM6DSL_ACC_GYRO_FF_EV_STATUS_t;

#define LSM6DSL_ACC_GYRO_Z_TAP_MASK  	0x01
typedef enum {
  	LSM6DSL_ACC_GYRO_Z_TAP_NOT_DETECTED = 0x00,
  	LSM6DSL_ACC_GYRO_Z_TAP_DETECTED = 0x01,
} LSM6DSL_ACC_GYRO_Z_TAP_t;

#define LSM6DSL_ACC_GYRO_Y_TAP_MASK  	0x02
typedef enum {
  	LSM6DSL_ACC_GYRO_Y_TAP_NOT_DETECTED = 0x00,
  	LSM6DSL_ACC_GYRO_Y_TAP_DETECTED = 0x02,
} LSM6DSL_ACC_GYRO_Y_TAP_t;

#define LSM6DSL_ACC_GYRO_X_TAP_MASK  	0x04
typedef enum {
  	LSM6DSL_ACC_GYRO_X_TAP_NOT_DETECTED = 0x00,
  	LSM6DSL_ACC_GYRO_X_TAP_DETECTED = 0x04,
} LSM6DSL_ACC_GYRO_X_TAP_t;

#define LSM6DSL_ACC_GYRO_TAP_SIGN_MASK  	0x08
typedef enum {
  	LSM6DSL_ACC_GYRO_TAP_SIGN_POS_SIGN = 0x00,
  	LSM6DSL_ACC_GYRO_TAP_SIGN_NEG_SIGN = 0x08,
} LSM6DSL_ACC_GYRO_TAP_SIGN_t;

#define LSM6DSL_ACC_GYRO_DOUBLE_TAP_EV_STATUS_MASK  	0x10
typedef enum {
  	LSM6DSL_ACC_GYRO_DOUBLE_TAP_EV_STATUS_NOT_DETECTED = 0x00,
  	LSM6DSL_ACC_GYRO_DOUBLE_TAP_EV_STATUS_DETECTED = 0x10,
} LSM6DSL_ACC_GYRO_DOUBLE_TAP_EV_STATUS_t;

#define LSM6DSL_ACC_GYRO_SINGLE_TAP_EV_STATUS_MASK  	0x20
typedef enum {
  	LSM6DSL_ACC_GYRO_SINGLE_TAP_EV_STATUS_NOT_DETECTED = 0x00,
  	LSM6DSL_ACC_GYRO_SINGLE_TAP_EV_STATUS_DETECTED = 0x20,
} LSM6DSL_ACC_GYRO_SINGLE_TAP_EV_STATUS_t;

#define LSM6DSL_ACC_GYRO_TAP_EV_STATUS_MASK  	0x40
typedef enum {
  	LSM6DSL_ACC_GYRO_TAP_EV_STATUS_NOT_DETECTED = 0x00,
  	LSM6DSL_ACC_GYRO_TAP_EV_STATUS_DETECTED = 0x40,
} LSM6DSL_ACC_GYRO_TAP_EV_STATUS_t;

#define LSM6DSL_ACC_GYRO_DSD_XL_MASK  	0x01
typedef enum {
  	LSM6DSL_ACC_GYRO_DSD_XL_NOT_DETECTED = 0x00,
  	LSM6DSL_ACC_GYRO_DSD_XL_DETECTED = 0x01,
} LSM6DSL_ACC_GYRO_DSD_XL_t;

#define LSM6DSL_ACC_GYRO_DSD_XH_MASK  	0x02
typedef enum {
  	LSM6DSL_ACC_GYRO_DSD_XH_NOT_DETECTED = 0x00,
  	LSM6DSL_ACC_GYRO_DSD_XH_DETECTED = 0x02,
} LSM6DSL_ACC_GYRO_DSD_XH_t;

#define LSM6DSL_ACC_GYRO_DSD_YL_MASK  	0x04
typedef enum {
  	LSM6DSL_ACC_GYRO_DSD_YL_NOT_DETECTED = 0x00,
  	LSM6DSL_ACC_GYRO_DSD_YL_DETECTED = 0x04,
} LSM6DSL_ACC_GYRO_DSD_YL_t;

#define LSM6DSL_ACC_GYRO_DSD_YH_MASK  	0x08
typedef enum {
  	LSM6DSL_ACC_GYRO_DSD_YH_NOT_DETECTED = 0x00,
  	LSM6DSL_ACC_GYRO_DSD_YH_DETECTED = 0x08,
} LSM6DSL_ACC_GYRO_DSD_YH_t;

#define LSM6DSL_ACC_GYRO_DSD_ZL_MASK  	0x10
typedef enum {
  	LSM6DSL_ACC_GYRO_DSD_ZL_NOT_DETECTED = 0x00,
  	LSM6DSL_ACC_GYRO_DSD_ZL_DETECTED = 0x10,
} LSM6DSL_ACC_GYRO_DSD_ZL_t;

#define LSM6DSL_ACC_GYRO_DSD_ZH_MASK  	0x20
typedef enum {
  	LSM6DSL_ACC_GYRO_DSD_ZH_NOT_DETECTED = 0x00,
  	LSM6DSL_ACC_GYRO_DSD_ZH_DETECTED = 0x20,
} LSM6DSL_ACC_GYRO_DSD_ZH_t;

#define LSM6DSL_ACC_GYRO_D6D_EV_STATUS_MASK  	0x40
typedef enum {
  	LSM6DSL_ACC_GYRO_D6D_EV_STATUS_NOT_DETECTED = 0x00,
  	LSM6DSL_ACC_GYRO_D6D_EV_STATUS_DETECTED = 0x40,
} LSM6DSL_ACC_GYRO_D6D_EV_STATUS_t;

#define LSM6DSL_ACC_GYRO_XLDA_MASK  	0x01
typedef enum {
  	LSM6DSL_ACC_GYRO_XLDA_NO_DATA_AVAIL = 0x00,
  	LSM6DSL_ACC_GYRO_XLDA_DATA_AVAIL = 0x01,
} LSM6DSL_ACC_GYRO_XLDA_t;

#define LSM6DSL_ACC_GYRO_GDA_MASK  	0x02
typedef enum {
  	LSM6DSL_ACC_GYRO_GDA_NO_DATA_AVAIL = 0x00,
  	LSM6DSL_ACC_GYRO_GDA_DATA_AVAIL = 0x02,
} LSM6DSL_ACC_GYRO_GDA_t;

#define LSM6DSL_ACC_GYRO_TDA_MASK  	0x04
typedef enum {
  	LSM6DSL_ACC_GYRO_TDA_NO_DATA_AVAIL = 0x00,
  	LSM6DSL_ACC_GYRO_TDA_DATA_AVAIL = 0x04,
} LSM6DSL_ACC_GYRO_TDA_t;

#define LSM6DSL_ACC_GYRO_DIFF_FIFO_STATUS1_MASK      	0xFF
#define LSM6DSL_ACC_GYRO_DIFF_FIFO_STATUS1_POSITION  	0
#define LSM6DSL_ACC_GYRO_DIFF_FIFO_STATUS2_MASK         0xF
#define LSM6DSL_ACC_GYRO_DIFF_FIFO_STATUS2_POSITION  	0

#define LSM6DSL_ACC_GYRO_FIFO_EMPTY_MASK  	0x10
typedef enum {
  	LSM6DSL_ACC_GYRO_FIFO_EMPTY_FIFO_NOT_EMPTY = 0x00,
  	LSM6DSL_ACC_GYRO_FIFO_EMPTY_FIFO_EMPTY = 0x10,
} LSM6DSL_ACC_GYRO_FIFO_EMPTY_t;

#define LSM6DSL_ACC_GYRO_FIFO_FULL_MASK  	0x20
typedef enum {
  	LSM6DSL_ACC_GYRO_FIFO_FULL_FIFO_NOT_FULL = 0x00,
  	LSM6DSL_ACC_GYRO_FIFO_FULL_FIFO_FULL = 0x20,
} LSM6DSL_ACC_GYRO_FIFO_FULL_t;

#define LSM6DSL_ACC_GYRO_OVERRUN_MASK  	0x40
typedef enum {
  	LSM6DSL_ACC_GYRO_OVERRUN_NO_OVERRUN = 0x00,
  	LSM6DSL_ACC_GYRO_OVERRUN_OVERRUN = 0x40,
} LSM6DSL_ACC_GYRO_OVERRUN_t;

#define LSM6DSL_ACC_GYRO_WTM_MASK  	0x80
typedef enum {
  	LSM6DSL_ACC_GYRO_WTM_BELOW_WTM = 0x00,
  	LSM6DSL_ACC_GYRO_WTM_ABOVE_OR_EQUAL_WTM = 0x80,
} LSM6DSL_ACC_GYRO_WTM_t;

#define LSM6DSL_ACC_GYRO_FIFO_STATUS3_PATTERN_MASK  	    0xFF
#define LSM6DSL_ACC_GYRO_FIFO_STATUS3_PATTERN_POSITION  	0
#define LSM6DSL_ACC_GYRO_FIFO_STATUS4_PATTERN_MASK      	0x03
#define LSM6DSL_ACC_GYRO_FIFO_STATUS4_PATTERN_POSITION  	0

#define LSM6DSL_ACC_GYRO_SENS_HUB_END_MASK  	0x01
typedef enum {
  	LSM6DSL_ACC_GYRO_SENS_HUB_END_STILL_ONGOING = 0x00,
  	LSM6DSL_ACC_GYRO_SENS_HUB_END_OP_COMPLETED = 0x01,
} LSM6DSL_ACC_GYRO_SENS_HUB_END_t;

#define LSM6DSL_ACC_GYRO_SOFT_IRON_END_MASK  	0x02
typedef enum {
  	LSM6DSL_ACC_GYRO_SOFT_IRON_END_NOT_COMPLETED = 0x00,
  	LSM6DSL_ACC_GYRO_SOFT_IRON_END_COMPLETED = 0x02,
} LSM6DSL_ACC_GYRO_SOFT_IRON_END_t;

#define LSM6DSL_ACC_GYRO_HARD_IRON_STAT_MASK  	0x04
typedef enum {
  	LSM6DSL_ACC_GYRO_HARD_IRON_NORMAL = 0x00,
  	LSM6DSL_ACC_GYRO_HARD_IRON_FAIL = 0x04,
} LSM6DSL_ACC_GYRO_SOFT_HARD_IRON_STAT_t;

#define LSM6DSL_ACC_GYRO_STEP_OVERFLOW_MASK  	0x08
typedef enum {
  	LSM6DSL_ACC_GYRO_PEDO_STEP_IN_RANGE = 0x00,
  	LSM6DSL_ACC_GYRO_PEDO_ESTEP_OVERFLOW = 0x08,
} LSM6DSL_ACC_GYRO_STEP_OVERFLOW_t;

#define LSM6DSL_ACC_GYRO_PEDO_EV_STATUS_MASK  	0x10
typedef enum {
  	LSM6DSL_ACC_GYRO_PEDO_EV_STATUS_NOT_DETECTED = 0x00,
  	LSM6DSL_ACC_GYRO_PEDO_EV_STATUS_DETECTED = 0x10,
} LSM6DSL_ACC_GYRO_PEDO_EV_STATUS_t;

#define LSM6DSL_ACC_GYRO_TILT_EV_STATUS_MASK  	0x20
typedef enum {
  	LSM6DSL_ACC_GYRO_TILT_EV_STATUS_NOT_DETECTED = 0x00,
  	LSM6DSL_ACC_GYRO_TILT_EV_STATUS_DETECTED = 0x20,
} LSM6DSL_ACC_GYRO_TILT_EV_STATUS_t;

#define LSM6DSL_ACC_GYRO_SIGN_MOT_EV_STATUS_MASK  	0x40
typedef enum {
  	LSM6DSL_ACC_GYRO_SIGN_MOT_EV_STATUS_NOT_DETECTED = 0x00,
  	LSM6DSL_ACC_GYRO_SIGN_MOT_EV_STATUS_DETECTED = 0x40,
} LSM6DSL_ACC_GYRO_SIGN_MOT_EV_STATUS_t;

#define LSM6DSL_ACC_GYRO_STEP_COUNT_DELTA_MASK  	0x80
typedef enum {
  	LSM6DSL_ACC_GYRO_NO_STEP_COUNT_IN_DELTA = 0x00,
  	LSM6DSL_ACC_GYRO_STEP_COUNT_IN_DELTA		 =0x80,
} LSM6DSL_ACC_GYRO_STEP_COUNT_DELTA_t;

#define LSM6DSL_ACC_GYRO_LIR_MASK  	0x01
typedef enum {
  	LSM6DSL_ACC_GYRO_LIR_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_LIR_ENABLED = 0x01,
} LSM6DSL_ACC_GYRO_LIR_t;

#define LSM6DSL_ACC_GYRO_TAP_Z_EN_MASK  	0x02
typedef enum {
  	LSM6DSL_ACC_GYRO_TAP_Z_EN_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_TAP_Z_EN_ENABLED = 0x02,
} LSM6DSL_ACC_GYRO_TAP_Z_EN_t;

#define LSM6DSL_ACC_GYRO_TAP_Y_EN_MASK  	0x04
typedef enum {
  	LSM6DSL_ACC_GYRO_TAP_Y_EN_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_TAP_Y_EN_ENABLED = 0x04,
} LSM6DSL_ACC_GYRO_TAP_Y_EN_t;

#define LSM6DSL_ACC_GYRO_TAP_X_EN_MASK  	0x08
typedef enum {
  	LSM6DSL_ACC_GYRO_TAP_X_EN_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_TAP_X_EN_ENABLED = 0x08,
} LSM6DSL_ACC_GYRO_TAP_X_EN_t;

#define LSM6DSL_ACC_GYRO_SLOPE_FDS_MASK  	0x10
typedef enum {
  	LSM6DSL_ACC_GYRO_SLOPE_FDS_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_SLOPE_FDS_ENABLED = 0x10,
} LSM6DSL_ACC_GYRO_SLOPE_FDS_t;

#define LSM6DSL_ACC_GYRO_INT_EN_MASK  	0x80
typedef enum {
  	LSM6DSL_ACC_GYRO_BASIC_INT_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_BASIC_INT_ENABLED = 0x80,
} LSM6DSL_ACC_GYRO_INT_EN_t;

#define LSM6DSL_ACC_GYRO_TAP_THS_MASK  	0x1F
#define LSM6DSL_ACC_GYRO_TAP_THS_POSITION  	0

#define LSM6DSL_ACC_GYRO_SIXD_THS_MASK  	0x60
typedef enum {
  	LSM6DSL_ACC_GYRO_SIXD_THS_80_degree = 0x00,
  	LSM6DSL_ACC_GYRO_SIXD_THS_70_degree = 0x20,
  	LSM6DSL_ACC_GYRO_SIXD_THS_60_degree = 0x40,
  	LSM6DSL_ACC_GYRO_SIXD_THS_50_degree = 0x60,
} LSM6DSL_ACC_GYRO_SIXD_THS_t;

#define LSM6DSL_ACC_GYRO_D4D_MASK  	0x80
typedef enum {
  	LSM6DSL_ACC_GYRO_D4D_DIS = 0x00,
  	LSM6DSL_ACC_GYRO_D4D_EN = 0x80,
} LSM6DSL_ACC_GYRO_D4D_t;

#define LSM6DSL_ACC_GYRO_SHOCK_MASK  	0x03
#define LSM6DSL_ACC_GYRO_SHOCK_POSITION  	0

#define LSM6DSL_ACC_GYRO_QUIET_MASK  	0x0C
#define LSM6DSL_ACC_GYRO_QUIET_POSITION  	2

#define LSM6DSL_ACC_GYRO_DUR_MASK  	0xF0
#define LSM6DSL_ACC_GYRO_DUR_POSITION  	4

#define LSM6DSL_ACC_GYRO_WK_THS_MASK  	0x3F
#define LSM6DSL_ACC_GYRO_WK_THS_POSITION  	0

#define LSM6DSL_ACC_GYRO_SINGLE_DOUBLE_TAP_MASK  	0x80
typedef enum {
  	LSM6DSL_ACC_GYRO_SINGLE_DOUBLE_TAP_SINGLE_TAP = 0x00,
  	LSM6DSL_ACC_GYRO_SINGLE_DOUBLE_TAP_DOUBLE_TAP = 0x80,
} LSM6DSL_ACC_GYRO_SINGLE_DOUBLE_TAP_t;

#define LSM6DSL_ACC_GYRO_SLEEP_DUR_MASK  	0x0F
#define LSM6DSL_ACC_GYRO_SLEEP_DUR_POSITION  	0

#define LSM6DSL_ACC_GYRO_TIMER_HR_MASK  	0x10
typedef enum {
  	LSM6DSL_ACC_GYRO_TIMER_HR_6_4ms = 0x00,
  	LSM6DSL_ACC_GYRO_TIMER_HR_25us = 0x10,
} LSM6DSL_ACC_GYRO_TIMER_HR_t;

#define LSM6DSL_ACC_GYRO_WAKE_DUR_MASK  	0x60
#define LSM6DSL_ACC_GYRO_WAKE_DUR_POSITION  	5

#define LSM6DSL_ACC_GYRO_FF_FREE_FALL_DUR_MASK  	0xF8
#define LSM6DSL_ACC_GYRO_FF_FREE_FALL_DUR_POSITION  	3
#define LSM6DSL_ACC_GYRO_FF_WAKE_UP_DUR_MASK  	0x80
#define LSM6DSL_ACC_GYRO_FF_WAKE_UP_DUR_POSITION  	7

#define LSM6DSL_ACC_GYRO_FF_THS_MASK  	0x07
typedef enum {
  	LSM6DSL_ACC_GYRO_FF_THS_156mg = 0x00,
  	LSM6DSL_ACC_GYRO_FF_THS_219mg = 0x01,
  	LSM6DSL_ACC_GYRO_FF_THS_250mg = 0x02,
  	LSM6DSL_ACC_GYRO_FF_THS_312mg = 0x03,
  	LSM6DSL_ACC_GYRO_FF_THS_344mg = 0x04,
  	LSM6DSL_ACC_GYRO_FF_THS_406mg = 0x05,
  	LSM6DSL_ACC_GYRO_FF_THS_469mg = 0x06,
  	LSM6DSL_ACC_GYRO_FF_THS_500mg = 0x07,
} LSM6DSL_ACC_GYRO_FF_THS_t;

#define LSM6DSL_ACC_GYRO_INT1_TIMER_MASK  	0x01
typedef enum {
  	LSM6DSL_ACC_GYRO_INT1_TIMER_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_INT1_TIMER_ENABLED = 0x01,
} LSM6DSL_ACC_GYRO_INT1_TIMER_t;

#define LSM6DSL_ACC_GYRO_INT1_TILT_MASK  	0x02
typedef enum {
  	LSM6DSL_ACC_GYRO_INT1_TILT_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_INT1_TILT_ENABLED = 0x02,
} LSM6DSL_ACC_GYRO_INT1_TILT_t;

#define LSM6DSL_ACC_GYRO_INT1_6D_MASK  	0x04
typedef enum {
  	LSM6DSL_ACC_GYRO_INT1_6D_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_INT1_6D_ENABLED = 0x04,
} LSM6DSL_ACC_GYRO_INT1_6D_t;

#define LSM6DSL_ACC_GYRO_INT1_TAP_MASK  	0x08
typedef enum {
  	LSM6DSL_ACC_GYRO_INT1_TAP_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_INT1_TAP_ENABLED = 0x08,
} LSM6DSL_ACC_GYRO_INT1_TAP_t;

#define LSM6DSL_ACC_GYRO_INT1_FF_MASK  	0x10
typedef enum {
  	LSM6DSL_ACC_GYRO_INT1_FF_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_INT1_FF_ENABLED = 0x10,
} LSM6DSL_ACC_GYRO_INT1_FF_t;

#define LSM6DSL_ACC_GYRO_INT1_WU_MASK  	0x20
typedef enum {
  	LSM6DSL_ACC_GYRO_INT1_WU_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_INT1_WU_ENABLED = 0x20,
} LSM6DSL_ACC_GYRO_INT1_WU_t;

#define LSM6DSL_ACC_GYRO_INT1_SINGLE_TAP_MASK  	0x40
typedef enum {
  	LSM6DSL_ACC_GYRO_INT1_SINGLE_TAP_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_INT1_SINGLE_TAP_ENABLED = 0x40,
} LSM6DSL_ACC_GYRO_INT1_SINGLE_TAP_t;

#define LSM6DSL_ACC_GYRO_INT1_SLEEP_MASK  	0x80
typedef enum {
  	LSM6DSL_ACC_GYRO_INT1_SLEEP_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_INT1_SLEEP_ENABLED = 0x80,
} LSM6DSL_ACC_GYRO_INT1_SLEEP_t;

#define LSM6DSL_ACC_GYRO_INT2_IRON_MASK  	0x01
typedef enum {
  	LSM6DSL_ACC_GYRO_INT2_IRON_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_INT2_IRON_ENABLED = 0x01,
} LSM6DSL_ACC_GYRO_INT2_IRON_t;

#define LSM6DSL_ACC_GYRO_INT2_TILT_MASK  	0x02
typedef enum {
  	LSM6DSL_ACC_GYRO_INT2_TILT_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_INT2_TILT_ENABLED = 0x02,
} LSM6DSL_ACC_GYRO_INT2_TILT_t;

#define LSM6DSL_ACC_GYRO_INT2_6D_MASK  	0x04
typedef enum {
  	LSM6DSL_ACC_GYRO_INT2_6D_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_INT2_6D_ENABLED = 0x04,
} LSM6DSL_ACC_GYRO_INT2_6D_t;

#define LSM6DSL_ACC_GYRO_INT2_TAP_MASK  	0x08
typedef enum {
  	LSM6DSL_ACC_GYRO_INT2_TAP_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_INT2_TAP_ENABLED = 0x08,
} LSM6DSL_ACC_GYRO_INT2_TAP_t;

#define LSM6DSL_ACC_GYRO_INT2_FF_MASK  	0x10
typedef enum {
  	LSM6DSL_ACC_GYRO_INT2_FF_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_INT2_FF_ENABLED = 0x10,
} LSM6DSL_ACC_GYRO_INT2_FF_t;

#define LSM6DSL_ACC_GYRO_INT2_WU_MASK  	0x20
#define LSM6DSL_ACC_GYRO_INT2_SINGLE_TAP_MASK  	0x40
typedef enum {
  	LSM6DSL_ACC_GYRO_INT2_WU_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_INT2_WU_ENABLED = 0x20,
} LSM6DSL_ACC_GYRO_INT2_WU_t;

typedef enum {
  	LSM6DSL_ACC_GYRO_INT2_SINGLE_TAP_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_INT2_SINGLE_TAP_ENABLED = 0x40,
} LSM6DSL_ACC_GYRO_INT2_SINGLE_TAP_t;

#define LSM6DSL_ACC_GYRO_INT2_SLEEP_MASK  	0x80
typedef enum {
  	LSM6DSL_ACC_GYRO_INT2_SLEEP_DISABLED = 0x00,
  	LSM6DSL_ACC_GYRO_INT2_SLEEP_ENABLED = 0x80,
} LSM6DSL_ACC_GYRO_INT2_SLEEP_t;

#endif // LSM6DSL_REGISTER_DEF_H
