/**
 ******************************************************************************
 * @file    LSM6DSL_ACC_GYRO_driver.h
 * @author  MEMS Application Team
 * @version V1.5
 * @date    17-May-2016
 * @brief   LSM6DSL header driver file
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; COPYRIGHT(c) 2017 STMicroelectronics</center></h2>
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *   1. Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 *   3. Neither the name of STMicroelectronics nor the names of its contributors
 *      may be used to endorse or promote products derived from this software
 *      without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************
 */
/*
 * Based on STMicroelectronics LSM6DSL driver
 * Modified by Neon Smart Studio for W-Link
 */

#ifndef LSM6DSL_REGISTER_H
#define LSM6DSL_REGISTER_H

#include <stdint.h>

#include "LSM6DSL_IO.h"

#include "LSM6DSL_Def.h"

#include "LSM6DSL_Register_Def.h"

#ifdef __cplusplus
extern "C" {
#endif

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_WriteReg(uint8_t Reg, uint8_t *Bufp, uint16_t len);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_ReadReg(uint8_t Reg, uint8_t *Bufp, uint16_t len);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_WHO_AM_I(uint8_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_BDU(LSM6DSL_ACC_GYRO_BDU_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_BDU(LSM6DSL_ACC_GYRO_BDU_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_FS_XL(LSM6DSL_ACC_GYRO_FS_XL_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_FS_XL(LSM6DSL_ACC_GYRO_FS_XL_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_GetRawAccData(uint8_t *buff);
LSM6DSL_OpStatus LSM6DSL_ACC_Get_Acceleration(int *buff, bool from_fifo);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_ODR_XL(LSM6DSL_ACC_GYRO_ODR_XL_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_ODR_XL(LSM6DSL_ACC_GYRO_ODR_XL_t *p_value);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_translate_ODR_XL(LSM6DSL_ACC_GYRO_ODR_XL_t value, uint16_t *odr_hz_val);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_FS_G(LSM6DSL_ACC_GYRO_FS_G_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_FS_G(LSM6DSL_ACC_GYRO_FS_G_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_ODR_G(LSM6DSL_ACC_GYRO_ODR_G_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_ODR_G(LSM6DSL_ACC_GYRO_ODR_G_t *p_value);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_translate_ODR_G(LSM6DSL_ACC_GYRO_ODR_G_t value, uint16_t *odr_hz_val);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_GetRawGyroData(uint8_t *buff);
LSM6DSL_OpStatus LSM6DSL_ACC_Get_AngularRate(int *buff, uint8_t from_fifo);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_BW_SEL(LSM6DSL_ACC_GYRO_BW_SEL_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_BW_SEL(LSM6DSL_ACC_GYRO_BW_SEL_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_FS_125(LSM6DSL_ACC_GYRO_FS_125_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_FS_125(LSM6DSL_ACC_GYRO_FS_125_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_BLE(LSM6DSL_ACC_GYRO_BLE_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_BLE(LSM6DSL_ACC_GYRO_BLE_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_EmbeddedAccess(LSM6DSL_ACC_GYRO_EMB_ACC_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_EmbeddedAccess(LSM6DSL_ACC_GYRO_EMB_ACC_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_Stamping_Time_Frame(uint8_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_Stamping_Time_Frame(uint8_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_SYNC_RES_RATIO(LSM6DSL_ACC_GYRO_SYNC_RES_RATIO_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_SYNC_RES_RATIO(LSM6DSL_ACC_GYRO_SYNC_RES_RATIO_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_FIFO_Watermark(uint16_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_FIFO_Watermark(uint16_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_FIFO_TEMP(LSM6DSL_ACC_GYRO_FIFO_TEMP_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_FIFO_TEMP(LSM6DSL_ACC_GYRO_FIFO_TEMP_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_TIM_PEDO_FIFO_Write_En(LSM6DSL_ACC_GYRO_TIM_PEDO_FIFO_DRDY_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_TIM_PEDO_FIFO_Write_En(LSM6DSL_ACC_GYRO_TIM_PEDO_FIFO_DRDY_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_TIM_PEDO_FIFO_En(LSM6DSL_ACC_GYRO_TIM_PEDO_FIFO_EN_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_TIM_PEDO_FIFO_En(LSM6DSL_ACC_GYRO_TIM_PEDO_FIFO_EN_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_DEC_FIFO_XL(LSM6DSL_ACC_GYRO_DEC_FIFO_XL_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_DEC_FIFO_XL_val(uint16_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_DEC_FIFO_XL(LSM6DSL_ACC_GYRO_DEC_FIFO_XL_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_DEC_FIFO_G(LSM6DSL_ACC_GYRO_DEC_FIFO_G_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_DEC_FIFO_G_val(uint16_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_DEC_FIFO_G(LSM6DSL_ACC_GYRO_DEC_FIFO_G_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_DEC_FIFO_DS3(LSM6DSL_ACC_GYRO_DEC_FIFO_DS3_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_DEC_FIFO_DS3(LSM6DSL_ACC_GYRO_DEC_FIFO_DS3_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_DEC_FIFO_DS4(LSM6DSL_ACC_GYRO_DEC_FIFO_DS4_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_DEC_FIFO_DS4(LSM6DSL_ACC_GYRO_DEC_FIFO_DS4_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_HI_DATA_ONLY(LSM6DSL_ACC_GYRO_HI_DATA_ONLY_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_HI_DATA_ONLY(LSM6DSL_ACC_GYRO_HI_DATA_ONLY_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_STOP_ON_FTH(LSM6DSL_ACC_GYRO_STOP_ON_FTH_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_STOP_ON_FTH(LSM6DSL_ACC_GYRO_STOP_ON_FTH_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_FIFO_MODE(LSM6DSL_ACC_GYRO_FIFO_MODE_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_FIFO_MODE(LSM6DSL_ACC_GYRO_FIFO_MODE_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_ODR_FIFO(LSM6DSL_ACC_GYRO_ODR_FIFO_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_ODR_FIFO(LSM6DSL_ACC_GYRO_ODR_FIFO_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_DRDY_PULSE(LSM6DSL_ACC_GYRO_DRDY_PULSE_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_DRDY_PULSE(LSM6DSL_ACC_GYRO_DRDY_PULSE_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_DRDY_XL_on_INT1(LSM6DSL_ACC_GYRO_INT1_DRDY_XL_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_DRDY_XL_on_INT1(LSM6DSL_ACC_GYRO_INT1_DRDY_XL_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_DRDY_G_on_INT1(LSM6DSL_ACC_GYRO_INT1_DRDY_G_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_DRDY_G_on_INT1(LSM6DSL_ACC_GYRO_INT1_DRDY_G_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_BOOT_on_INT1(LSM6DSL_ACC_GYRO_INT1_BOOT_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_BOOT_on_INT1(LSM6DSL_ACC_GYRO_INT1_BOOT_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_FIFO_TSHLD_on_INT1(LSM6DSL_ACC_GYRO_INT1_FTH_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_FIFO_TSHLD_on_INT1(LSM6DSL_ACC_GYRO_INT1_FTH_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_OVERRUN_on_INT1(LSM6DSL_ACC_GYRO_INT1_OVR_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_OVERRUN_on_INT1(LSM6DSL_ACC_GYRO_INT1_OVR_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_FULL_FLAG_on_INT1(LSM6DSL_ACC_GYRO_INT1_FULL_FLAG_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_FULL_FLAG_on_INT1(LSM6DSL_ACC_GYRO_INT1_FULL_FLAG_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_SIGN_MOT_on_INT1(LSM6DSL_ACC_GYRO_INT1_SIGN_MOT_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_SIGN_MOT_on_INT1(LSM6DSL_ACC_GYRO_INT1_SIGN_MOT_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_STEP_DET_on_INT1(LSM6DSL_ACC_GYRO_INT1_PEDO_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_STEP_DET_on_INT1(LSM6DSL_ACC_GYRO_INT1_PEDO_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_DRDY_XL_on_INT2(LSM6DSL_ACC_GYRO_INT2_DRDY_XL_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_DRDY_XL_on_INT2(LSM6DSL_ACC_GYRO_INT2_DRDY_XL_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_DRDY_G_on_INT2(LSM6DSL_ACC_GYRO_INT2_DRDY_G_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_DRDY_G_on_INT2(LSM6DSL_ACC_GYRO_INT2_DRDY_G_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_DRDY_TEMP_on_INT2(LSM6DSL_ACC_GYRO_INT2_DRDY_TEMP_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_DRDY_TEMP_on_INT2(LSM6DSL_ACC_GYRO_INT2_DRDY_TEMP_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_FIFO_TSHLD_on_INT2(LSM6DSL_ACC_GYRO_INT2_FTH_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_FIFO_TSHLD_on_INT2(LSM6DSL_ACC_GYRO_INT2_FTH_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_OVERRUN_on_INT2(LSM6DSL_ACC_GYRO_INT2_OVR_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_OVERRUN_on_INT2(LSM6DSL_ACC_GYRO_INT2_OVR_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_FULL_FLAG_on_INT2(LSM6DSL_ACC_GYRO_INT2_FULL_FLAG_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_FULL_FLAG_on_INT2(LSM6DSL_ACC_GYRO_INT2_FULL_FLAG_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_STEP_COUNT_OV_on_INT2(LSM6DSL_ACC_GYRO_INT2_STEP_COUNT_OV_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_STEP_COUNT_OV_on_INT2(LSM6DSL_ACC_GYRO_INT2_STEP_COUNT_OV_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_STEP_DELTA_on_INT2(LSM6DSL_ACC_GYRO_INT2_STEP_DELTA_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_STEP_DELTA_on_INT2(LSM6DSL_ACC_GYRO_INT2_STEP_DELTA_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_SW_RESET(LSM6DSL_ACC_GYRO_SW_RESET_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_SW_RESET(LSM6DSL_ACC_GYRO_SW_RESET_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_IF_Addr_Incr(LSM6DSL_ACC_GYRO_IF_INC_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_IF_Addr_Incr(LSM6DSL_ACC_GYRO_IF_INC_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_SPI_Mode(LSM6DSL_ACC_GYRO_SIM_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_SPI_Mode(LSM6DSL_ACC_GYRO_SIM_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_PadSel(LSM6DSL_ACC_GYRO_PP_OD_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_PadSel(LSM6DSL_ACC_GYRO_PP_OD_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_INT_ACT_LEVEL(LSM6DSL_ACC_GYRO_INT_ACT_LEVEL_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_INT_ACT_LEVEL(LSM6DSL_ACC_GYRO_INT_ACT_LEVEL_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_BOOT(LSM6DSL_ACC_GYRO_BOOT_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_BOOT(LSM6DSL_ACC_GYRO_BOOT_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_LPF1_SEL_G(LSM6DSL_ACC_GYRO_LPF1_SEL_G_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_LPF1_SEL_G(LSM6DSL_ACC_GYRO_LPF1_SEL_G_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_I2C_DISABLE(LSM6DSL_ACC_GYRO_I2C_DISABLE_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_I2C_DISABLE(LSM6DSL_ACC_GYRO_I2C_DISABLE_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_DRDY_MSK(LSM6DSL_ACC_GYRO_DRDY_MSK_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_DRDY_MSK(LSM6DSL_ACC_GYRO_DRDY_MSK_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_INT2_ON_INT1(LSM6DSL_ACC_GYRO_INT2_ON_INT1_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_INT2_ON_INT1(LSM6DSL_ACC_GYRO_INT2_ON_INT1_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_SleepMode_G(LSM6DSL_ACC_GYRO_SLEEP_G_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_SleepMode_G(LSM6DSL_ACC_GYRO_SLEEP_G_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_SelfTest_XL(LSM6DSL_ACC_GYRO_ST_XL_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_SelfTest_XL(LSM6DSL_ACC_GYRO_ST_XL_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_SelfTest_G(LSM6DSL_ACC_GYRO_ST_G_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_SelfTest_G(LSM6DSL_ACC_GYRO_ST_G_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_DEN_Polarity(LSM6DSL_ACC_GYRO_DEN_LH_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_DEN_Polarity(LSM6DSL_ACC_GYRO_DEN_LH_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_CircularBurstMode(LSM6DSL_ACC_GYRO_ROUNDING_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_CircularBurstMode(LSM6DSL_ACC_GYRO_ROUNDING_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_LP_BW_G(LSM6DSL_ACC_GYRO_FTYPE_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_LP_BW_G(LSM6DSL_ACC_GYRO_FTYPE_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_UserOffsetWeight(LSM6DSL_ACC_GYRO_USR_OFF_W_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_UserOffsetWeight(LSM6DSL_ACC_GYRO_USR_OFF_W_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_LowPower_XL(LSM6DSL_ACC_GYRO_LP_XL_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_LowPower_XL(LSM6DSL_ACC_GYRO_LP_XL_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_DEN_LVL2_EN(LSM6DSL_ACC_GYRO_DEN_LVL2_EN_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_DEN_LVL2_EN(LSM6DSL_ACC_GYRO_DEN_LVL2_EN_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_DEN_LVL_EN(LSM6DSL_ACC_GYRO_DEN_LVL_EN_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_DEN_LVL_EN(LSM6DSL_ACC_GYRO_DEN_LVL_EN_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_ExternalTrigger(LSM6DSL_ACC_GYRO_DEN_EDGE_EN_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_ExternalTrigger(LSM6DSL_ACC_GYRO_DEN_EDGE_EN_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_RoundingOnStatusRegisters(LSM6DSL_ACC_GYRO_RND_STATUS_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_RoundingOnStatusRegisters(LSM6DSL_ACC_GYRO_RND_STATUS_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_HPM_G(LSM6DSL_ACC_GYRO_HPM_G_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_HPM_G(LSM6DSL_ACC_GYRO_HPM_G_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_HPFilter_En(LSM6DSL_ACC_GYRO_HP_EN_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_HPFilter_En(LSM6DSL_ACC_GYRO_HP_EN_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_LP_Mode(LSM6DSL_ACC_GYRO_LP_EN_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_LP_Mode(LSM6DSL_ACC_GYRO_LP_EN_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_ROUNDING_STATUS(LSM6DSL_ACC_GYRO_ROUNDING_STATUS_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_ROUNDING_STATUS(LSM6DSL_ACC_GYRO_ROUNDING_STATUS_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_HP_G_RST(LSM6DSL_ACC_GYRO_HP_G_RST_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_HP_G_RST(LSM6DSL_ACC_GYRO_HP_G_RST_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_LOW_PASS_ON_6D(LSM6DSL_ACC_GYRO_LOW_PASS_ON_6D_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_LOW_PASS_ON_6D(LSM6DSL_ACC_GYRO_LOW_PASS_ON_6D_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_HP_SLOPE_XL(LSM6DSL_ACC_GYRO_HP_SLOPE_XL_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_HP_SLOPE_XL(LSM6DSL_ACC_GYRO_HP_SLOPE_XL_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_InComposit(LSM6DSL_ACC_GYRO_IN_COMP_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_InComposit(LSM6DSL_ACC_GYRO_IN_COMP_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_HPfilterReference(LSM6DSL_ACC_GYRO_HP_REF_MODE_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_HPfilterReference(LSM6DSL_ACC_GYRO_HP_REF_MODE_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_HPCF_XL(LSM6DSL_ACC_GYRO_HPCF_XL_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_HPCF_XL(LSM6DSL_ACC_GYRO_HPCF_XL_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_LowPassFiltSel_XL(LSM6DSL_ACC_GYRO_LPF2_XL_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_LowPassFiltSel_XL(LSM6DSL_ACC_GYRO_LPF2_XL_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_SOFT(LSM6DSL_ACC_GYRO_SOFT_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_SOFT(LSM6DSL_ACC_GYRO_SOFT_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_SignifcantMotion(LSM6DSL_ACC_GYRO_SIGN_MOTION_EN_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_SignifcantMotion(LSM6DSL_ACC_GYRO_SIGN_MOTION_EN_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_PedoStepReset(LSM6DSL_ACC_GYRO_PEDO_RST_STEP_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_PedoStepReset(LSM6DSL_ACC_GYRO_PEDO_RST_STEP_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_FUNC_EN(LSM6DSL_ACC_GYRO_FUNC_EN_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_FUNC_EN(LSM6DSL_ACC_GYRO_FUNC_EN_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_TILT(LSM6DSL_ACC_GYRO_TILT_G_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_TILT(LSM6DSL_ACC_GYRO_TILT_G_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_PEDO(LSM6DSL_ACC_GYRO_PEDO_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_PEDO(LSM6DSL_ACC_GYRO_PEDO_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_TIMER(LSM6DSL_ACC_GYRO_TIMER_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_TIMER(LSM6DSL_ACC_GYRO_TIMER_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_I2C_MASTER_Enable(LSM6DSL_ACC_GYRO_MASTER_ON_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_I2C_MASTER_Enable(LSM6DSL_ACC_GYRO_MASTER_ON_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_IronCorrection_EN(LSM6DSL_ACC_GYRO_IRON_EN_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_IronCorrection_EN(LSM6DSL_ACC_GYRO_IRON_EN_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_PASS_THRU_MODE(LSM6DSL_ACC_GYRO_PASS_THRU_MODE_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_PASS_THRU_MODE(LSM6DSL_ACC_GYRO_PASS_THRU_MODE_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_PULL_UP_EN(LSM6DSL_ACC_GYRO_PULL_UP_EN_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_PULL_UP_EN(LSM6DSL_ACC_GYRO_PULL_UP_EN_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_SensorHUB_Trigger_Sel(LSM6DSL_ACC_GYRO_START_CONFIG_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_SensorHUB_Trigger_Sel(LSM6DSL_ACC_GYRO_START_CONFIG_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_DATA_VAL_SEL_FIFO(LSM6DSL_ACC_GYRO_DATA_VAL_SEL_FIFO_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_DATA_VAL_SEL_FIFO(LSM6DSL_ACC_GYRO_DATA_VAL_SEL_FIFO_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_DRDY_ON_INT1(LSM6DSL_ACC_GYRO_DRDY_ON_INT1_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_DRDY_ON_INT1(LSM6DSL_ACC_GYRO_DRDY_ON_INT1_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_Z_WU(LSM6DSL_ACC_GYRO_Z_WU_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_Y_WU(LSM6DSL_ACC_GYRO_Y_WU_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_X_WU(LSM6DSL_ACC_GYRO_X_WU_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_WU_EV_STATUS(LSM6DSL_ACC_GYRO_WU_EV_STATUS_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_SLEEP_EV_STATUS(LSM6DSL_ACC_GYRO_SLEEP_EV_STATUS_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_FF_EV_STATUS(LSM6DSL_ACC_GYRO_FF_EV_STATUS_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_Z_TAP(LSM6DSL_ACC_GYRO_Z_TAP_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_Y_TAP(LSM6DSL_ACC_GYRO_Y_TAP_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_X_TAP(LSM6DSL_ACC_GYRO_X_TAP_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_TAP_SIGN(LSM6DSL_ACC_GYRO_TAP_SIGN_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_DOUBLE_TAP_EV_STATUS(LSM6DSL_ACC_GYRO_DOUBLE_TAP_EV_STATUS_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_SINGLE_TAP_EV_STATUS(LSM6DSL_ACC_GYRO_SINGLE_TAP_EV_STATUS_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_TAP_EV_STATUS(LSM6DSL_ACC_GYRO_TAP_EV_STATUS_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_DSD_XL(LSM6DSL_ACC_GYRO_DSD_XL_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_DSD_XH(LSM6DSL_ACC_GYRO_DSD_XH_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_DSD_YL(LSM6DSL_ACC_GYRO_DSD_YL_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_DSD_YH(LSM6DSL_ACC_GYRO_DSD_YH_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_DSD_ZL(LSM6DSL_ACC_GYRO_DSD_ZL_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_DSD_ZH(LSM6DSL_ACC_GYRO_DSD_ZH_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_D6D_EV_STATUS(LSM6DSL_ACC_GYRO_D6D_EV_STATUS_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_XLDA(LSM6DSL_ACC_GYRO_XLDA_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_GDA(LSM6DSL_ACC_GYRO_GDA_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_TDA(LSM6DSL_ACC_GYRO_TDA_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_FIFONumOfEntries(uint16_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_FIFOEmpty(LSM6DSL_ACC_GYRO_FIFO_EMPTY_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_FIFOFull(LSM6DSL_ACC_GYRO_FIFO_FULL_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_OVERRUN(LSM6DSL_ACC_GYRO_OVERRUN_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_WaterMark(LSM6DSL_ACC_GYRO_WTM_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_FIFOPattern(uint16_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_SENS_HUB_END(LSM6DSL_ACC_GYRO_SENS_HUB_END_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_SOFT_IRON_END(LSM6DSL_ACC_GYRO_SOFT_IRON_END_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_HardIron(LSM6DSL_ACC_GYRO_SOFT_HARD_IRON_STAT_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_STEP_OVERFLOW(LSM6DSL_ACC_GYRO_STEP_OVERFLOW_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_PEDO_EV_STATUS(LSM6DSL_ACC_GYRO_PEDO_EV_STATUS_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_TILT_EV_STATUS(LSM6DSL_ACC_GYRO_TILT_EV_STATUS_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_SIGN_MOT_EV_STATUS(LSM6DSL_ACC_GYRO_SIGN_MOT_EV_STATUS_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_STEP_COUNT_DELTA(LSM6DSL_ACC_GYRO_STEP_COUNT_DELTA_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_LIR(LSM6DSL_ACC_GYRO_LIR_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_LIR(LSM6DSL_ACC_GYRO_LIR_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_TAP_Z_EN(LSM6DSL_ACC_GYRO_TAP_Z_EN_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_TAP_Z_EN(LSM6DSL_ACC_GYRO_TAP_Z_EN_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_TAP_Y_EN(LSM6DSL_ACC_GYRO_TAP_Y_EN_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_TAP_Y_EN(LSM6DSL_ACC_GYRO_TAP_Y_EN_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_TAP_X_EN(LSM6DSL_ACC_GYRO_TAP_X_EN_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_TAP_X_EN(LSM6DSL_ACC_GYRO_TAP_X_EN_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_SLOPE_FDS(LSM6DSL_ACC_GYRO_SLOPE_FDS_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_SLOPE_FDS(LSM6DSL_ACC_GYRO_SLOPE_FDS_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_BASIC_INT(LSM6DSL_ACC_GYRO_INT_EN_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_BASIC_INT(LSM6DSL_ACC_GYRO_INT_EN_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_TAP_THS(uint8_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_TAP_THS(uint8_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_SIXD_THS(LSM6DSL_ACC_GYRO_SIXD_THS_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_SIXD_THS(LSM6DSL_ACC_GYRO_SIXD_THS_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_D4D(LSM6DSL_ACC_GYRO_D4D_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_D4D(LSM6DSL_ACC_GYRO_D4D_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_SHOCK_Duration(uint8_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_SHOCK_Duration(uint8_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_QUIET_Duration(uint8_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_QUIET_Duration(uint8_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_DUR(uint8_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_DUR(uint8_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_WK_THS(uint8_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_WK_THS(uint8_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_SINGLE_DOUBLE_TAP_EV(LSM6DSL_ACC_GYRO_SINGLE_DOUBLE_TAP_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_SINGLE_DOUBLE_TAP_EV(LSM6DSL_ACC_GYRO_SINGLE_DOUBLE_TAP_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_SLEEP_DUR(uint8_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_SLEEP_DUR(uint8_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_TIMER_HR(LSM6DSL_ACC_GYRO_TIMER_HR_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_TIMER_HR(LSM6DSL_ACC_GYRO_TIMER_HR_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_WAKE_DUR(uint8_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_WAKE_DUR(uint8_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_FF_Duration(uint8_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_FF_Duration(uint8_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_FF_THS(LSM6DSL_ACC_GYRO_FF_THS_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_FF_THS(LSM6DSL_ACC_GYRO_FF_THS_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_TimerEvRouteInt1(LSM6DSL_ACC_GYRO_INT1_TIMER_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_TimerEvRouteInt1(LSM6DSL_ACC_GYRO_INT1_TIMER_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_TiltEvOnInt1(LSM6DSL_ACC_GYRO_INT1_TILT_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_TiltEvOnInt1(LSM6DSL_ACC_GYRO_INT1_TILT_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_6DEvOnInt1(LSM6DSL_ACC_GYRO_INT1_6D_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_6DEvOnInt1(LSM6DSL_ACC_GYRO_INT1_6D_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_TapEvOnInt1(LSM6DSL_ACC_GYRO_INT1_TAP_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_TapEvOnInt1(LSM6DSL_ACC_GYRO_INT1_TAP_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_FFEvOnInt1(LSM6DSL_ACC_GYRO_INT1_FF_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_FFEvOnInt1(LSM6DSL_ACC_GYRO_INT1_FF_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_WUEvOnInt1(LSM6DSL_ACC_GYRO_INT1_WU_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_WUEvOnInt1(LSM6DSL_ACC_GYRO_INT1_WU_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_SingleTapOnInt1(LSM6DSL_ACC_GYRO_INT1_SINGLE_TAP_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_SingleTapOnInt1(LSM6DSL_ACC_GYRO_INT1_SINGLE_TAP_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_SleepEvOnInt1(LSM6DSL_ACC_GYRO_INT1_SLEEP_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_SleepEvOnInt1(LSM6DSL_ACC_GYRO_INT1_SLEEP_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_MagCorrection_Int2(LSM6DSL_ACC_GYRO_INT2_IRON_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_MagCorrection_Int2(LSM6DSL_ACC_GYRO_INT2_IRON_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_TiltEvOnInt2(LSM6DSL_ACC_GYRO_INT2_TILT_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_TiltEvOnInt2(LSM6DSL_ACC_GYRO_INT2_TILT_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_6DEvOnInt2(LSM6DSL_ACC_GYRO_INT2_6D_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_6DEvOnInt2(LSM6DSL_ACC_GYRO_INT2_6D_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_TapEvOnInt2(LSM6DSL_ACC_GYRO_INT2_TAP_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_TapEvOnInt2(LSM6DSL_ACC_GYRO_INT2_TAP_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_FFEvOnInt2(LSM6DSL_ACC_GYRO_INT2_FF_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_FFEvOnInt2(LSM6DSL_ACC_GYRO_INT2_FF_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_WUEvOnInt2(LSM6DSL_ACC_GYRO_INT2_WU_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_WUEvOnInt2(LSM6DSL_ACC_GYRO_INT2_WU_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_SingleTapOnInt2(LSM6DSL_ACC_GYRO_INT2_SINGLE_TAP_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_SingleTapOnInt2(LSM6DSL_ACC_GYRO_INT2_SINGLE_TAP_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_SleepEvOnInt2(LSM6DSL_ACC_GYRO_INT2_SLEEP_t newValue);
LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_R_SleepEvOnInt2(LSM6DSL_ACC_GYRO_INT2_SLEEP_t *p_value);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_Get_GetFIFOData(uint8_t *buff);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_Get_GetTimestamp(uint8_t *buff);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_Get_GetStepCounter(uint8_t *buff);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_W_PedoThreshold(uint8_t newValue);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_SH0_Program(uint8_t SlvAddr, uint8_t Reg, uint8_t len);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_SH_init_SI_Matrix(uint8_t *SI_matrix);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_SH0_ReadMem(uint8_t SlvAddr, uint8_t Reg, uint8_t *Bufp, uint8_t len, uint8_t stop);

LSM6DSL_OpStatus LSM6DSL_ACC_GYRO_SH0_WriteByte(uint8_t SlvAddr, uint8_t Reg, uint8_t Bufp);

#ifdef __cplusplus
}
#endif

#endif // LSM6DSL_REGISTER_H
